# Generated by Django 4.2.2 on 2023-06-12 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Meditation',
            fields=[
                ('med_ID', models.AutoField(primary_key=True, serialize=False)),
                ('med_Fname', models.CharField(max_length=100)),
                ('med_Lname', models.CharField(max_length=100)),
                ('med_type', models.CharField(max_length=100)),
                ('med_description', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Meditation_Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('med_page_url', models.CharField(max_length=150)),
                ('med_page_details', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Page_Visit',
            fields=[
                ('visit_ID', models.AutoField(primary_key=True, serialize=False)),
                ('visit_date_time', models.DateField(auto_now_add=True)),
                ('med_visitor_IP', models.GenericIPAddressField()),
                ('med_page_url', models.URLField()),
                ('user_ID', models.CharField(max_length=100)),
                ('med_ID', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='QuoteOfTheDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quote', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_ID', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=20)),
                ('registration_date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
