# Generated by Django 4.2.2 on 2023-06-13 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meditations', '0003_rename_med_fname_meditation_genre'),
    ]

    operations = [
        migrations.AddField(
            model_name='meditation',
            name='meditation_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
