# Generated by Django 4.2.2 on 2023-06-26 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meditations', '0004_meditation_meditation_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('profile_page_ID', models.AutoField(primary_key=True, serialize=False)),
                ('profile_ID', models.CharField(max_length=100)),
                ('user_ID', models.CharField(max_length=100)),
            ],
        ),
    ]
