# Generated by Django 4.2.2 on 2023-06-27 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meditations', '0005_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='ForgotPassword',
            fields=[
                ('forgot_page_ID', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
    ]
